travis:
  secure:
    BINSTAR_TOKEN: M8lUWNkkoOadPKQrW7li1QruNuoCHmQFbe/MAzT6z2MlXPHCKUKh1jslg5jZRQyE4gp9b8NGrX4+PFPRbiwD/VvPMOkXDJWYnDluaV+hmS5GoRtIl1X7cctp0TnCbIlxq8usPddFdHAJv/5A2TAMcR9zlhpGLCOm26R2hSIoVvmWkMtjIVZKRme62Jn3Tc4HWQcUsyp+h8DjAZoPkmhjU+9/omQPJG6NHbNHnVVVwf1KEDDf3SA3HJSixukM1Qa9o38frHCqKyYyFkW65eQx9ZEb4U3lGL4G+8mBnA3X9R8nW8833IWGaIeBWfshkRHndpPO9ixwsaoeioywrCSsR8iXB4vn/U4bXneWvkMHd+5hn20Itg6bIRSj+9QD3rYaMniFjo1iD/9GAuVXVeh1+B0Cw4tP6v+XL0FFM+Mm1AK4C/4b00tl+Q/ELqP6TS5FyldSShRpgfr23/JBxLDK+ky3KJBpv5KZhC92p8yfmJjm33qvOaXvifIpVX2jrlbQjEk6JGMPZp/dqpi/xJjPYjqLs3QrqlZ27K84g7qKlBpiki5uHzdQRlQOE+G48D40tqXc6QzYTML3AG3IvkFYn+08Uv/FQ/1Y7519zanfpudjrkzTbdbULcx8+0viRnrAR1TtTqL848N0Aa4N+aBMjZqtEPoBj8/dl9hn1/+QEu0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
